name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
      - run: ./gradlew build
      - run: ./gradlew nativeCompile
      - uses: actions/upload-artifact@v3
        with:
          name: allure-testops-utils-windows-latest
          path: ./build/native/nativeCompile/allure-testops-utils
